backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: images
collections:
  - name: "navigation"
    label: "Navigation"
    files:
    - label: "navigation"
      name: "navigation"
      file: "content/navigation.md"
      widget: "list"
      fields: 
        - label: Items
          name: items
          widget: object
          fields:
            - {label: Name, name: name, widget: string, default: "Home"}
            - {label: Slug, name: slug, widget: string, default: "/"}