backend:
  name: git-gateway
  branch: master

media_folder: public/images
public_folder: images
logo_url: public/images/drama_fruit_logo.png
display_url: https://dramafruit.netlify.app

collections:
  - name: "home"
    label: "Home"
    label_singular: "image"
    folder: "content"
    create: true
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text 1", name: "image_alt", widget: "string"}
      - {label: "Image2", name: "image2", widget: "image"}
      - {label: "Alt Text 2", name: "image2_alt", widget: "string"}
      - {label: "Image3", name: "image3", widget: "image"}
      - {label: "Alt Text 3", name: "image3_alt", widget: "string"}
      - {label: "Image4", name: "image4", widget: "image"}
      - {label: "Alt Text 4", name: "image4_alt", widget: "string"}
      - {label: "Image5", name: "image5", widget: "image"}
      - {label: "Alt Text 5", name: "image5_alt", widget: "string"}
      - {label: "Image6", name: "image6", widget: "image"}
      - {label: "Alt Text 6", name: "image6_alt", widget: "string"}