backend:
  name: git-gateway
  branch: master

media_folder: public/images
public_folder: images
logo_url: public/images/drama_fruit_logo.png
display_url: https://dramafruit.netlify.app

collections:
  - name: "home"
    label: "Home"
    label_singular: "image"
    folder: "content"
    create: true
    fields:
      - {
          label: "First Image", name: "first_image", widget: "object", fields:
            - {label: "Image", name: "image", widget: "image"}
            - {label: "Alt Text", name: "alt_text", widget: "string"}
        }
      - {label: "Image2", name: "image2", widget: "image"}
      - {label: "Alt Text 2", name: "alt_text_2", widget: "string"}
      - {label: "Image3", name: "image3", widget: "image"}
      - {label: "Alt Text 3", name: "alt_text_3", widget: "string"}
      - {label: "Image4", name: "image4", widget: "image"}
      - {label: "Alt Text 4", name: "alt_text_4", widget: "string"}
      - {label: "Image5", name: "image5", widget: "image"}
      - {label: "Alt Text 5", name: "alt_text_5", widget: "string"}
      - {label: "Image6", name: "image6", widget: "image"}
      - {label: "Alt Text 6", name: "alt_text_6", widget: "string"}