backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: images
collections:
  - name: "navigation"
    label: "Navigation"
    files:
    - label: "Navigation"
      name: "navigation"
      file: "content/navigation.md"
      widget: "object"
      collapsed: true
      fields:
        {label: "Home", name: "home", widget: "string"}