backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Navigation", name: "navigation", widget: "array"}
        - { label: "Publish Date", name: "date", widget: "datetime" }