backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: images
collections:
  - name: "home"
    label: "Home"
    files:
    - label: "home"
      name: "Home"
      file: "content/home.md"
      widget: "list"
      fields: 
        - label: Images
          name: images
          widget: object
          fields:
            - { label: Image1, name: image1, widget: image }
            - { label: Image2, name: image2, widget: image }