backend:
  name: git-gateway
  branch: master

media_folder: public/images
public_folder: images
logo_url: public/images/drama_fruit_logo.png
display_url: https://dramafruit.netlify.app

collections:
  - name: "home"
    label: "Home"
    label_singular: "image"
    folder: "content"
    create: true
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt_text", widget: "string"}
      - {label: "Image2", name: "image2", widget: "image"}
      - {label: "Alt Text", name: "alt_text", widget: "string"}
      - {label: "Image3", name: "image3", widget: "image"}
      - {label: "Alt Text", name: "alt_text", widget: "string"}
      - {label: "Image4", name: "image4", widget: "image"}
      - {label: "Alt Text", name: "alt_text", widget: "string"}
      - {label: "Image5", name: "image5", widget: "image"}
      - {label: "Alt Text", name: "alt_text", widget: "string"}
      