backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: images
collections:
  - name: "navigation"
    label: "Navigation"
    files:
    - label: "navigation"
      name: "navigation"
      file: "content/navigation.md"
      widget: "list"
      fields: 
        - { label: "Item", name: "item", widget: "string" }
        - { label: "Slug", name: "slug", widget: "string" }
      default:
        - { item: "Home", slug: "/" }
        - { item: "About", slug: "/about" }