backend:
  name: git-gateway
  branch: master

media_folder: public/images
public_folder: images
logo_url: public/images/drama_fruit_logo.png
display_url: https://dramafruit.netlify.app

collections:
  - name: "home"
    label: "Home"
    label_singular: "image"
    folder: "content"
    create: true
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "image_alt", widget: "string"}
      - {label: "Subtitle", name: "image_subtitle", widget: "string"}
      - {label: "Price", name: "image_price", widget: "string"}
      - {label: "Image2", name: "image2", widget: "image"}
      - {label: "Alt Text", name: "image2_alt", widget: "string"}
      - {label: "Subtitle", name: "image2_subtitle", widget: "string"}
      - {label: "Price", name: "image2_price", widget: "string"}
      - {label: "Image3", name: "image3", widget: "image"}
      - {label: "Alt Text", name: "image3_alt", widget: "string"}
      - {label: "Subtitle", name: "image3_subtitle", widget: "string"}
      - {label: "Price", name: "image3_price", widget: "string"}
      - {label: "Image4", name: "image4", widget: "image"}
      - {label: "Alt Text", name: "image4_alt", widget: "string"}
      - {label: "Subtitle", name: "image4_subtitle", widget: "string"}
      - {label: "Price", name: "image4_price", widget: "string"}
      - {label: "Image5", name: "image5", widget: "image"}
      - {label: "Alt Text", name: "image5_alt", widget: "string"}
      - {label: "Subtitle", name: "image5_subtitle", widget: "string"}
      - {label: "Price", name: "image5_price", widget: "string"}
      - {label: "Image6", name: "image6", widget: "image"}
      - {label: "Alt Text", name: "image6_alt", widget: "string"}
      - {label: "Subtitle", name: "image6_subtitle", widget: "string"}
      - {label: "Price", name: "image6_price", widget: "string"}
  
  - name: "products"
    label: "Products"
    label_singular: "Product"
    folder: "content/products"
    create: true
    fields:
      - {label: "Name", name: "product_name", widget: "string"}
      - {label: "Description", name: "product_description", widget: "markdown"}
      - {label: "Image", name: "product_image", widget: "image"}
      - {label: "Image Alt Text", name: "product_image_alt", widget: "string"}
      - {label: "Price", name: "product_price", widget: "number"}
      - {label: "URL", name: "product_slug", widget: "string"}