backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: images
collections:
  - navigation: "navigation"
    label: "Navigation"
    files:
    - label: "navigation"
      name: "navigation"
      file: "content/navigation.md"
      fields: 
        - { label: "Navigation", name: "navigation", widget: "list"}
        - { label: "Publish Date", name: "date", widget: "datetime" }