backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: images
collections:
  - name: "navigation"
    label: "Navigation"
    files:
    - label: "navigation"
      name: "navigation"
      file: "content/navigation.md"
      fields: 
        - label: "Navigation"
        name: "navigation"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Home", name: "home", widget: "string"}