backend:
  name: git-gateway
  branch: master

media_folder: public/images
public_folder: images
logo_url: public/images/drama_fruit_logo.png
display_url: https://dramafruit.netlify.app

collections:
  - name: "home"
    label: "Home"
    folder: "content"
    create: true
      fields:
        - { label: Image1, name: image1, widget: image }
        - { label: Image2, name: image2, widget: image }
        - { label: Image3, name: image3, widget: image }
        - { label: Image4, name: image4, widget: image }
        - { label: Image5, name: image5, widget: image }
