backend:
  name: git-gateway
  branch: cloudinary

media_library:
  name: cloudinary

media_folder: public/images
public_folder: images
logo_url: https://raw.githubusercontent.com/derrmru/drama-fruit/master/public/images/Drama%20Gif.gif
display_url: https://dramafruit.netlify.app

collections:
  - name: "home"
    label: "Home"
    label_singular: "image"
    folder: "content"
    create: true
    fields:
      - {
          label: "Home Showcase 1", 
          name: "home_showcase_1", 
          widget: "relation", 
          collection: "products", 
          search_fields: ["product_name"], 
          value_field: "product_name", 
          display_fields: ["product_name"],
        }
      - {
          label: "Home Showcase 2", 
          name: "home_showcase_2", 
          widget: "relation", 
          collection: "products", 
          search_fields: ["product_name"], 
          value_field: "product_name", 
          display_fields: ["product_name"],
        }
      - {
          label: "Home Showcase 3", 
          name: "home_showcase_3", 
          widget: "relation", 
          collection: "products", 
          search_fields: ["product_name"], 
          value_field: "product_name", 
          display_fields: ["product_name"],
        }
      - {
          label: "Home Showcase 4", 
          name: "home_showcase_4", 
          widget: "relation", 
          collection: "products", 
          search_fields: ["product_name"], 
          value_field: "product_name", 
          display_fields: ["product_name"],
        }
      - {
          label: "Home Showcase 5", 
          name: "home_showcase_5", 
          widget: "relation", 
          collection: "products", 
          search_fields: ["product_name"], 
          value_field: "product_name", 
          display_fields: ["product_name"],
        }
      - {
          label: "Home Showcase 6", 
          name: "home_showcase_6", 
          widget: "relation", 
          collection: "products", 
          search_fields: ["product_name"], 
          value_field: "product_name", 
          display_fields: ["product_name"],
        }
  
  - name: "products"
    label: "Products"
    label_singular: "Product"
    folder: "content/products"
    create: true
    fields:
      - {label: "Name", name: "product_name", widget: "string"}
      - {label: "Description", name: "product_description", widget: "markdown"}
      - {label: "Image", name: "product_image", widget: "image"}
      - {label: "Image Alt Text", name: "product_image_alt", widget: "string"}
      - {label: "Price", name: "product_price", widget: "number"}
      - {label: "Stock", name: "product_stock", width: "number"}